models/inventory.py
from utils.db import db


class Inventory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    price = db.Column(db.Float, nullable=False)
    mac_address = db.Column(db.String(17), nullable=False)
    serial_number = db.Column(db.String(20), nullable=False)
    manufacturer = db.Column(db.String(50), nullable=False)
    description = db.Column(db.String(100), nullable=False)

    def __init__(self, name, price, mac_address, serial_number, manufacturer, description):
        self.name = name
        self.price = price
        self.mac_address = mac_address
        self.serial_number = serial_number
        self.manufacturer = manufacturer
        self.description = description

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv

from routes.routes import inventory
from utils.db import db
import os

load_dotenv()

app = Flask(__name__)

app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('SQLALCHEMY_DATABASE_URI')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

#SQLAlchemy(app)
db.init_app(app)

app.register_blueprint(inventory)

routes/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.inventory import Inventory
from utils.db import db

inventory = Blueprint('inventory', __name__)


@inventory.route('/')
def index():

    items = Inventory.query.all()

    return render_template('index.html', items=items)


@inventory.route('/add', methods=['GET', 'POST'])
def add():

    if request.method == 'POST':
        name = request.form['name']
        price = request.form['price']
        mac_address = request.form['mac_address']
        serial_number = request.form['serial_number']
        manufacturer = request.form['manufacturer']
        description = request.form['description']

        new_item = Inventory(name, price, mac_address,
                             serial_number, manufacturer, description)
        db.session.add(new_item)
        db.session.commit()

        flash('Item added successfully', 'success')

        return redirect(url_for('inventory.index'))

    return render_template('add.html')


@inventory.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):

    item = Inventory.query.get(id)

    if request.method == 'POST':

        item.name = request.form['name']
        item.price = request.form['price']
        item.mac_address = request.form['mac_address']
        item.serial_number = request.form['serial_number']
        item.manufacturer = request.form['manufacturer']
        item.description = request.form['description']

        db.session.commit()

        flash('Item updated successfully', 'success')

        return redirect(url_for('inventory.index'))

    return render_template('edit.html', item=item)


@inventory.route('/delete/<int:id>')
def delete(id):

    item = Inventory.query.get(id)
    db.session.delete(item)
    db.session.commit()

    flash('Item deleted successfully', 'success')

    return redirect(url_for('inventory.index'))

templates/add.html
<!doctype html>
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            <!-- place navbar here -->
        </header>
        <main>

            <h1>Add Item</h1>
        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

templates/edit.html
{% extends 'layout.html' %} {% block content %}

<div class="custom-container">
  <h1 class="header-title header-title-warning">Edit Item Page</h1>

  <form class="row g-3" action="/edit/{{ item.id }}" method="POST">
    <div class="col-md-6">
      <label for="name" class="form-label">Name</label>
      <input
        type="text"
        name="name"
        placeholder="Name"
        class="form-control"
        value="{{ item.name }}"
      />
    </div>

    <div class="col-md-6">
      <label for="price" class="form-label">Price</label>
      <input
        type="text"
        name="price"
        placeholder="Price"
        class="form-control"
        value="{{ item.price }}"
      />
    </div>

    <div class="col-md-4">
      <label for="mac_address" class="form-label">Mac Address</label>
      <input
        type="text"
        name="mac_address"
        placeholder="Mac Address"
        class="form-control"
        value="{{ item.mac_address }}"
      />
    </div>
    <div class="col-md-4">
      <label for="serial_number" class="form-label">Serial Number</label>
      <input
        type="text"
        name="serial_number"
        placeholder="Serial Number"
        class="form-control"
        value="{{ item.serial_number }}"
      />
    </div>
    <div class="col-md-4">
      <label for="manufacturer" class="form-label">Manufacturer</label>
      <input
        type="text"
        name="manufacturer"
        placeholder="Manufacturer"
        class="form-control"
        value="{{ item.manufacturer }}"
      />
    </div>

    <div class="col-12">
      <label for="description" class="form-label">Description</label>
      <input
        type="text"
        name="description"
        placeholder="Description"
        class="form-control"
        value="{{ item.description }}"
      />
    </div>

    <div class="col-12">
      <button class="btn btn-primary" type="submit">Edit</button>
      <a href="{{ url_for('inventory.index') }}" class="btn btn-danger"
        >Cancel</a
      >
    </div>
  </form>
</div>

{% endblock %}

templates/index.html
{% extends 'layout.html' %} 

{% block content %} 

{% with messages = get_flashed_messages() %} 
    {% if messages %} 
        {% for message in messages %}

        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong class="text-success">Success</strong> {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {%endfor %}
    {% endif %}
{% endwith %}


<div class="custom-container">
    <h1 class="header-title header-title-primary mt-3">Invetory Management</h1>
    <div class="d-grid gap-2 d-md-flex justify-content-start justify-content-md-end mt-3 mb-4 ml-3">
        <a href="{{ url_for('inventory.add') }}" class="btn btn-success ">
            <i class="fa fa-plus"></i> Add Item
        </a>
    </div>
    
    <table class="table">
        <thead class="table-primary ">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Mac Address</th>
                <th scope="col">Serial Number</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Description</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.mac_address }}</td>
                <td>{{ item.serial_number }}</td>
                <td>{{ item.manufacturer }}</td>
                <td>{{ item.description }}</td>
                <td>
                    <div class="d-flex gap-2">
                        <a href="{{ url_for('inventory.edit', id=item.id) }}" class="btn btn-primary">
                            <i class="fa fa-edit fa-xs"></i>
                        </a>
                        <a href="{{ url_for('inventory.delete', id=item.id) }}" class="btn btn-danger">
                            <i class="fa fa-trash fa-xs"></i>
                        </a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Invetory Management App</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
      integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  </head>

  <body>
    <main>{% block content %} {% endblock content %}</main>

    <!-- Bootstrap JavaScript Libraries -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </body>
</html>